language: node_js
node_js:
- "0.10"
before_script: npm install coveralls istanbul
script: node_modules/.bin/istanbul cover --report lcovonly node_modules/mocha/bin/_mocha
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- rm -rf ./coverage
